name: flowner
description: "A state management package for Flutter, offering simplicity, efficiency, and scalability."
version: 1.0.0
homepage: https://github.com/14h4i/flowner

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
