name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Kiểm tra mã nguồn từ repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Thiết lập Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '<flutter-version>' # Thay <flutter-version> bằng phiên bản Flutter bạn muốn, hoặc bỏ qua để dùng bản mới nhất.

    # Cài đặt các dependencies
    - name: Install dependencies
      run: flutter pub get

    # Chạy kiểm tra
    - name: Run tests
      run: flutter test
