name: Flutter Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run tests
    - name: Run tests
      run: flutter test
